name: flutter_query_builder
description: Instead of focusing on the details of writing queries, you'll be able to focus on the basic logic of your app. Thus, you will simplify the read and write operations in your database. This will certainly facilitate the development process.
version: 1.0.2
homepage: "https://github.com/emran619/flutter_query_builder/blob/main/lib/flutter_query_builder.dart"
repository: "https://github.com/emran619/flutter_query_builder"

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.9"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
